### ISSUE TITLE
Put Change Requests behind Beta Powers flag

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2089]

**Comment by sethmcknight** [comment]
@CarsonF do you know where the PR for this is?

**Comment by CarsonF** [comment]
Oh looks like I merged it 4 days ago https://github.com/SeedCompany/cord-field/pull/896

**Comment by sethmcknight** [comment]
Huh, looks like this is still showing up for all roles in Dev rather than just those with the role of Beta Tester. Can we get someone to look at that and get this functioning in Dev? I want to confirm this works before we push to Prod.

**Comment by CarsonF** [comment]
Problem is the powers code in the DB which do not account for roles/powers being removed.

Seth had a role with this power but it was but it remained when the role was removed.
